# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.idl import local_routing_service_pb2 as idl_dot_local__routing__service__pb2


class LocalRoutingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/deeproute.idl.local_routing_service.LocalRoutingService/Init',
                request_serializer=idl_dot_local__routing__service__pb2.LocalRoutingInitRequest.SerializeToString,
                response_deserializer=idl_dot_local__routing__service__pb2.LocalRoutingInitResponse.FromString,
                )
        self.Proc = channel.unary_unary(
                '/deeproute.idl.local_routing_service.LocalRoutingService/Proc',
                request_serializer=idl_dot_local__routing__service__pb2.LocalRoutingProcRequest.SerializeToString,
                response_deserializer=idl_dot_local__routing__service__pb2.LocalRoutingProcResponse.FromString,
                )


class LocalRoutingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Proc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalRoutingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=idl_dot_local__routing__service__pb2.LocalRoutingInitRequest.FromString,
                    response_serializer=idl_dot_local__routing__service__pb2.LocalRoutingInitResponse.SerializeToString,
            ),
            'Proc': grpc.unary_unary_rpc_method_handler(
                    servicer.Proc,
                    request_deserializer=idl_dot_local__routing__service__pb2.LocalRoutingProcRequest.FromString,
                    response_serializer=idl_dot_local__routing__service__pb2.LocalRoutingProcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deeproute.idl.local_routing_service.LocalRoutingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocalRoutingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deeproute.idl.local_routing_service.LocalRoutingService/Init',
            idl_dot_local__routing__service__pb2.LocalRoutingInitRequest.SerializeToString,
            idl_dot_local__routing__service__pb2.LocalRoutingInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Proc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deeproute.idl.local_routing_service.LocalRoutingService/Proc',
            idl_dot_local__routing__service__pb2.LocalRoutingProcRequest.SerializeToString,
            idl_dot_local__routing__service__pb2.LocalRoutingProcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
