# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.idl import perception_service_pb2 as idl_dot_perception__service__pb2


class PerceptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/deeproute.idl.perception_service.PerceptionService/Init',
                request_serializer=idl_dot_perception__service__pb2.PerceptionInitRequest.SerializeToString,
                response_deserializer=idl_dot_perception__service__pb2.PerceptionInitResponse.FromString,
                )
        self.Proc = channel.unary_unary(
                '/deeproute.idl.perception_service.PerceptionService/Proc',
                request_serializer=idl_dot_perception__service__pb2.PerceptionProcRequest.SerializeToString,
                response_deserializer=idl_dot_perception__service__pb2.PerceptionProcResponse.FromString,
                )


class PerceptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Proc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerceptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=idl_dot_perception__service__pb2.PerceptionInitRequest.FromString,
                    response_serializer=idl_dot_perception__service__pb2.PerceptionInitResponse.SerializeToString,
            ),
            'Proc': grpc.unary_unary_rpc_method_handler(
                    servicer.Proc,
                    request_deserializer=idl_dot_perception__service__pb2.PerceptionProcRequest.FromString,
                    response_serializer=idl_dot_perception__service__pb2.PerceptionProcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deeproute.idl.perception_service.PerceptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PerceptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deeproute.idl.perception_service.PerceptionService/Init',
            idl_dot_perception__service__pb2.PerceptionInitRequest.SerializeToString,
            idl_dot_perception__service__pb2.PerceptionInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Proc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deeproute.idl.perception_service.PerceptionService/Proc',
            idl_dot_perception__service__pb2.PerceptionProcRequest.SerializeToString,
            idl_dot_perception__service__pb2.PerceptionProcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PredictionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/deeproute.idl.perception_service.PredictionService/Init',
                request_serializer=idl_dot_perception__service__pb2.PredictionInitRequest.SerializeToString,
                response_deserializer=idl_dot_perception__service__pb2.PredictionInitResponse.FromString,
                )
        self.Proc = channel.unary_unary(
                '/deeproute.idl.perception_service.PredictionService/Proc',
                request_serializer=idl_dot_perception__service__pb2.PredictionProcRequest.SerializeToString,
                response_deserializer=idl_dot_perception__service__pb2.PredictionProcResponse.FromString,
                )


class PredictionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Proc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=idl_dot_perception__service__pb2.PredictionInitRequest.FromString,
                    response_serializer=idl_dot_perception__service__pb2.PredictionInitResponse.SerializeToString,
            ),
            'Proc': grpc.unary_unary_rpc_method_handler(
                    servicer.Proc,
                    request_deserializer=idl_dot_perception__service__pb2.PredictionProcRequest.FromString,
                    response_serializer=idl_dot_perception__service__pb2.PredictionProcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deeproute.idl.perception_service.PredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deeproute.idl.perception_service.PredictionService/Init',
            idl_dot_perception__service__pb2.PredictionInitRequest.SerializeToString,
            idl_dot_perception__service__pb2.PredictionInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Proc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deeproute.idl.perception_service.PredictionService/Proc',
            idl_dot_perception__service__pb2.PredictionProcRequest.SerializeToString,
            idl_dot_perception__service__pb2.PredictionProcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
