# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drapi/navigation_map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64rapi/navigation_map.proto\x12\x11\x64r.navigation_map*B\n\tRoadClass\x12\x0e\n\nRC_HIGHWAY\x10\x00\x12\x17\n\x13RC_URBAN_EXPRESSWAY\x10\x01\x12\x0c\n\x08RC_OTHER\x10\x63\x62\x06proto3')

_ROADCLASS = DESCRIPTOR.enum_types_by_name['RoadClass']
RoadClass = enum_type_wrapper.EnumTypeWrapper(_ROADCLASS)
RC_HIGHWAY = 0
RC_URBAN_EXPRESSWAY = 1
RC_OTHER = 99


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROADCLASS._serialized_start=49
  _ROADCLASS._serialized_end=115
# @@protoc_insertion_point(module_scope)
