# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drapi/unified_navigation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64rapi/unified_navigation.proto\x12\x14\x64r.common.navigation\"I\n\x0eSpeedLimitInfo\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x1a\n\x12remaining_distance\x18\x02 \x01(\r\x12\x0c\n\x04type\x18\x03 \x01(\r\"\x8a\x01\n\x0fSpeedLimitInfos\x12\x37\n\tspd_limit\x18\x01 \x01(\x0b\x32$.dr.common.navigation.SpeedLimitInfo\x12>\n\x10\x63\x61mera_spd_limit\x18\x02 \x01(\x0b\x32$.dr.common.navigation.SpeedLimitInfo\"\x89\x01\n\x0eNavigationInfo\x12\x35\n\x0bsource_type\x18\x01 \x02(\x0e\x32 .dr.common.navigation.SourceType\x12@\n\x11speed_limit_infos\x18\x02 \x01(\x0b\x32%.dr.common.navigation.SpeedLimitInfos*1\n\nSourceType\x12\n\n\x06ST_GWM\x10\x00\x12\t\n\x05ST_GL\x10\x01\x12\x0c\n\x08ST_SMART\x10\x02')

_SOURCETYPE = DESCRIPTOR.enum_types_by_name['SourceType']
SourceType = enum_type_wrapper.EnumTypeWrapper(_SOURCETYPE)
ST_GWM = 0
ST_GL = 1
ST_SMART = 2


_SPEEDLIMITINFO = DESCRIPTOR.message_types_by_name['SpeedLimitInfo']
_SPEEDLIMITINFOS = DESCRIPTOR.message_types_by_name['SpeedLimitInfos']
_NAVIGATIONINFO = DESCRIPTOR.message_types_by_name['NavigationInfo']
SpeedLimitInfo = _reflection.GeneratedProtocolMessageType('SpeedLimitInfo', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDLIMITINFO,
  '__module__' : 'drapi.unified_navigation_pb2'
  # @@protoc_insertion_point(class_scope:dr.common.navigation.SpeedLimitInfo)
  })
_sym_db.RegisterMessage(SpeedLimitInfo)

SpeedLimitInfos = _reflection.GeneratedProtocolMessageType('SpeedLimitInfos', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDLIMITINFOS,
  '__module__' : 'drapi.unified_navigation_pb2'
  # @@protoc_insertion_point(class_scope:dr.common.navigation.SpeedLimitInfos)
  })
_sym_db.RegisterMessage(SpeedLimitInfos)

NavigationInfo = _reflection.GeneratedProtocolMessageType('NavigationInfo', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATIONINFO,
  '__module__' : 'drapi.unified_navigation_pb2'
  # @@protoc_insertion_point(class_scope:dr.common.navigation.NavigationInfo)
  })
_sym_db.RegisterMessage(NavigationInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOURCETYPE._serialized_start=412
  _SOURCETYPE._serialized_end=461
  _SPEEDLIMITINFO._serialized_start=56
  _SPEEDLIMITINFO._serialized_end=129
  _SPEEDLIMITINFOS._serialized_start=132
  _SPEEDLIMITINFOS._serialized_end=270
  _NAVIGATIONINFO._serialized_start=273
  _NAVIGATIONINFO._serialized_end=410
# @@protoc_insertion_point(module_scope)
