# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivers/inu/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import geometry_pb2 as common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64rivers/inu/config.proto\x12\x15\x64\x65\x65proute.drivers.inu\x1a\x15\x63ommon/geometry.proto\"\xef\x05\n\x06\x43onfig\x12\x1a\n\x12\x65nable_calibration\x18\x01 \x01(\x08\x12=\n\x1alevel_arm_imu_to_gnss_ant1\x18\x02 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12&\n\x1emisalignment_angle_imu_to_gnss\x18\x03 \x01(\x01\x12H\n%misalignment_pry_angle_imu_to_vehicle\x18\x04 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12\x31\n\x0egyro_zero_bias\x18\x05 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12\x31\n\x0e\x61\x63\x63\x65_zero_bias\x18\x06 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12\x43\n init_gnss_imu_level_arm_variance\x18\x07 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12\"\n\x1ainit_gnss_heading_variance\x18\x08 \x01(\x01\x12\x19\n\x11gyro_scale_factor\x18\t \x01(\x01\x12\x19\n\x11\x61\x63\x63\x65_scale_factor\x18\n \x01(\x01\x12;\n\x13gyro_coupling_error\x18\x0b \x01(\x0b\x32\x1e.deeproute.drivers.inu.Matrix3\x12;\n\x13\x61\x63\x63\x65_coupling_error\x18\x0c \x01(\x0b\x32\x1e.deeproute.drivers.inu.Matrix3\x12K\n(level_arm_imu_to_left_non_steering_wheel\x18\r \x01(\x0b\x32\x19.deeproute.common.Vector3\x12L\n)level_arm_imu_to_right_non_steering_wheel\x18\x0e \x01(\x0b\x32\x19.deeproute.common.Vector3\"~\n\x07Matrix3\x12%\n\x02\x63\x30\x18\x01 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12%\n\x02\x63\x31\x18\x02 \x01(\x0b\x32\x19.deeproute.common.Vector3\x12%\n\x02\x63\x32\x18\x03 \x01(\x0b\x32\x19.deeproute.common.Vector3')



_CONFIG = DESCRIPTOR.message_types_by_name['Config']
_MATRIX3 = DESCRIPTOR.message_types_by_name['Matrix3']
Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'drivers.inu.config_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.inu.Config)
  })
_sym_db.RegisterMessage(Config)

Matrix3 = _reflection.GeneratedProtocolMessageType('Matrix3', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX3,
  '__module__' : 'drivers.inu.config_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.inu.Matrix3)
  })
_sym_db.RegisterMessage(Matrix3)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=75
  _CONFIG._serialized_end=826
  _MATRIX3._serialized_start=828
  _MATRIX3._serialized_end=954
# @@protoc_insertion_point(module_scope)
