# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trip/bag_recorded.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17trip/bag_recorded.proto\x12\x0e\x64\x65\x65proute.trip\"E\n\x0b\x42\x61gRecorded\x12\x10\n\x08\x62\x61g_name\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x04\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x04')



_BAGRECORDED = DESCRIPTOR.message_types_by_name['BagRecorded']
BagRecorded = _reflection.GeneratedProtocolMessageType('BagRecorded', (_message.Message,), {
  'DESCRIPTOR' : _BAGRECORDED,
  '__module__' : 'trip.bag_recorded_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.trip.BagRecorded)
  })
_sym_db.RegisterMessage(BagRecorded)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BAGRECORDED._serialized_start=43
  _BAGRECORDED._serialized_end=112
# @@protoc_insertion_point(module_scope)
