# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trip/trigger_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18trip/trigger_event.proto\x12\x0e\x64\x65\x65proute.trip\"\xe4\x03\n\x0cTriggerEvent\x12\x11\n\ttrip_name\x18\x01 \x01(\t\x12\x19\n\x11\x62\x61\x63kward_time_sec\x18\x02 \x01(\r\x12\x18\n\x10\x66orward_time_sec\x18\x03 \x01(\r\x12\x0e\n\x06\x63\x61r_id\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x15\n\rtrigger_level\x18\x06 \x01(\t\x12\x1b\n\x13system_timestamp_ns\x18\x07 \x01(\t\x12\x13\n\x0bmodule_name\x18\x08 \x01(\t\x12\x14\n\x0ctrigger_type\x18\t \x01(\t\x12\x11\n\tbags_name\x18\n \x03(\t\x12\x1f\n\x17\x62\x61gs_start_timestamp_ns\x18\x0b \x03(\t\x12\x1d\n\x15\x62\x61gs_end_timestamp_ns\x18\x0c \x03(\t\x12\x0f\n\x07task_id\x18\r \x01(\x05\x12\x18\n\x10security_officer\x18\x0e \x01(\t\x12\x0e\n\x06tester\x18\x0f \x01(\t\x12\x17\n\x0fpackage_version\x18\x10 \x03(\t\x12\x16\n\x0e\x64river_version\x18\x11 \x01(\t\x12\x14\n\x0ctrigger_name\x18\x12 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x13 \x01(\r\x12\r\n\x05\x65vent\x18\x14 \x01(\t\x12\x12\n\nevent_uuid\x18\x15 \x01(\t')



_TRIGGEREVENT = DESCRIPTOR.message_types_by_name['TriggerEvent']
TriggerEvent = _reflection.GeneratedProtocolMessageType('TriggerEvent', (_message.Message,), {
  'DESCRIPTOR' : _TRIGGEREVENT,
  '__module__' : 'trip.trigger_event_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.trip.TriggerEvent)
  })
_sym_db.RegisterMessage(TriggerEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIGGEREVENT._serialized_start=45
  _TRIGGEREVENT._serialized_end=529
# @@protoc_insertion_point(module_scope)
