# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map/map_engine_setting_cmd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n map/map_engine_setting_cmd.proto\x12\rdeeproute.map\"r\n\x1eMapEngineSettingCommandRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12<\n\x14variable_lane_switch\x18\x02 \x01(\x0e\x32\x1e.deeproute.map.MapEngineSwitch\"\xc9\x01\n\x1fMapEngineSettingCommandResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x45\n\x06status\x18\x02 \x01(\x0b\x32\x35.deeproute.map.MapEngineSettingCommandResponse.Status\x1aK\n\x06Status\x12\x30\n\x04\x63ode\x18\x01 \x01(\x0e\x32\".deeproute.map.MapEngineSwitchCode\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t*\x84\x01\n\x0fMapEngineSwitch\x12\x1d\n\x19MAP_ENGINE_SWITCH_NOT_SET\x10\x00\x12\x1d\n\x19MAP_ENGINE_SWITCH_DEFAULT\x10\x01\x12\x18\n\x14MAP_ENGINE_SWITCH_ON\x10\x02\x12\x19\n\x15MAP_ENGINE_SWITCH_OFF\x10\x03*T\n\x13MapEngineSwitchCode\x12\x1d\n\x19MAP_ENGINE_SWITCH_SUCCESS\x10\x00\x12\x1e\n\x1aMAP_ENGINE_SWITCH_INTERNAL\x10\x01')

_MAPENGINESWITCH = DESCRIPTOR.enum_types_by_name['MapEngineSwitch']
MapEngineSwitch = enum_type_wrapper.EnumTypeWrapper(_MAPENGINESWITCH)
_MAPENGINESWITCHCODE = DESCRIPTOR.enum_types_by_name['MapEngineSwitchCode']
MapEngineSwitchCode = enum_type_wrapper.EnumTypeWrapper(_MAPENGINESWITCHCODE)
MAP_ENGINE_SWITCH_NOT_SET = 0
MAP_ENGINE_SWITCH_DEFAULT = 1
MAP_ENGINE_SWITCH_ON = 2
MAP_ENGINE_SWITCH_OFF = 3
MAP_ENGINE_SWITCH_SUCCESS = 0
MAP_ENGINE_SWITCH_INTERNAL = 1


_MAPENGINESETTINGCOMMANDREQUEST = DESCRIPTOR.message_types_by_name['MapEngineSettingCommandRequest']
_MAPENGINESETTINGCOMMANDRESPONSE = DESCRIPTOR.message_types_by_name['MapEngineSettingCommandResponse']
_MAPENGINESETTINGCOMMANDRESPONSE_STATUS = _MAPENGINESETTINGCOMMANDRESPONSE.nested_types_by_name['Status']
MapEngineSettingCommandRequest = _reflection.GeneratedProtocolMessageType('MapEngineSettingCommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPENGINESETTINGCOMMANDREQUEST,
  '__module__' : 'map.map_engine_setting_cmd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.map.MapEngineSettingCommandRequest)
  })
_sym_db.RegisterMessage(MapEngineSettingCommandRequest)

MapEngineSettingCommandResponse = _reflection.GeneratedProtocolMessageType('MapEngineSettingCommandResponse', (_message.Message,), {

  'Status' : _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
    'DESCRIPTOR' : _MAPENGINESETTINGCOMMANDRESPONSE_STATUS,
    '__module__' : 'map.map_engine_setting_cmd_pb2'
    # @@protoc_insertion_point(class_scope:deeproute.map.MapEngineSettingCommandResponse.Status)
    })
  ,
  'DESCRIPTOR' : _MAPENGINESETTINGCOMMANDRESPONSE,
  '__module__' : 'map.map_engine_setting_cmd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.map.MapEngineSettingCommandResponse)
  })
_sym_db.RegisterMessage(MapEngineSettingCommandResponse)
_sym_db.RegisterMessage(MapEngineSettingCommandResponse.Status)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPENGINESWITCH._serialized_start=372
  _MAPENGINESWITCH._serialized_end=504
  _MAPENGINESWITCHCODE._serialized_start=506
  _MAPENGINESWITCHCODE._serialized_end=590
  _MAPENGINESETTINGCOMMANDREQUEST._serialized_start=51
  _MAPENGINESETTINGCOMMANDREQUEST._serialized_end=165
  _MAPENGINESETTINGCOMMANDRESPONSE._serialized_start=168
  _MAPENGINESETTINGCOMMANDRESPONSE._serialized_end=369
  _MAPENGINESETTINGCOMMANDRESPONSE_STATUS._serialized_start=294
  _MAPENGINESETTINGCOMMANDRESPONSE_STATUS._serialized_end=369
# @@protoc_insertion_point(module_scope)
