# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dsm/dsm_supervison.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64sm/dsm_supervison.proto\x12\x06\x64r.dsm\"7\n\x10StartTopicNotify\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x0e\n\x06topics\x18\x02 \x03(\tb\x06proto3')



_STARTTOPICNOTIFY = DESCRIPTOR.message_types_by_name['StartTopicNotify']
StartTopicNotify = _reflection.GeneratedProtocolMessageType('StartTopicNotify', (_message.Message,), {
  'DESCRIPTOR' : _STARTTOPICNOTIFY,
  '__module__' : 'dsm.dsm_supervison_pb2'
  # @@protoc_insertion_point(class_scope:dr.dsm.StartTopicNotify)
  })
_sym_db.RegisterMessage(StartTopicNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTTOPICNOTIFY._serialized_start=36
  _STARTTOPICNOTIFY._serialized_end=91
# @@protoc_insertion_point(module_scope)
