# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart/parking/smart_lp_parking_map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.smart.parking import smart_parking_common_pb2 as smart_dot_parking_dot_smart__parking__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(smart/parking/smart_lp_parking_map.proto\x12\rsmart.parking\x1a(smart/parking/smart_parking_common.proto\"\x86\x02\n\tLPMapData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12#\n\x05route\x18\x05 \x03(\x0b\x32\x14.smart.parking.Point\x12\x33\n\x0eparking_spaces\x18\x06 \x03(\x0b\x32\x1b.smart.parking.ParkingSpace\x12\x31\n\rmap_obstacles\x18\x07 \x03(\x0b\x32\x1a.smart.parking.MapObstacle\x12\x15\n\rcreation_time\x18\x08 \x01(\x05\x12\x16\n\x0etotal_distance\x18\t \x01(\x02\"{\n\x07MapInfo\x12\x0e\n\x06map_id\x18\x01 \x01(\x05\x12\x34\n\x0eoperation_type\x18\x02 \x01(\x0e\x32\x1c.smart.parking.OperatingType\x12*\n\x08map_data\x18\x03 \x01(\x0b\x32\x18.smart.parking.LPMapData\"7\n\x0bMapInfoList\x12(\n\x08map_info\x18\x01 \x03(\x0b\x32\x16.smart.parking.MapInfo*F\n\rOperatingType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06\x43RUISE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\n\n\x06MODIFY\x10\x03\x12\x07\n\x03\x41\x44\x44\x10\x04\x62\x06proto3')

_OPERATINGTYPE = DESCRIPTOR.enum_types_by_name['OperatingType']
OperatingType = enum_type_wrapper.EnumTypeWrapper(_OPERATINGTYPE)
NONE = 0
CRUISE = 1
DELETE = 2
MODIFY = 3
ADD = 4


_LPMAPDATA = DESCRIPTOR.message_types_by_name['LPMapData']
_MAPINFO = DESCRIPTOR.message_types_by_name['MapInfo']
_MAPINFOLIST = DESCRIPTOR.message_types_by_name['MapInfoList']
LPMapData = _reflection.GeneratedProtocolMessageType('LPMapData', (_message.Message,), {
  'DESCRIPTOR' : _LPMAPDATA,
  '__module__' : 'smart.parking.smart_lp_parking_map_pb2'
  # @@protoc_insertion_point(class_scope:smart.parking.LPMapData)
  })
_sym_db.RegisterMessage(LPMapData)

MapInfo = _reflection.GeneratedProtocolMessageType('MapInfo', (_message.Message,), {
  'DESCRIPTOR' : _MAPINFO,
  '__module__' : 'smart.parking.smart_lp_parking_map_pb2'
  # @@protoc_insertion_point(class_scope:smart.parking.MapInfo)
  })
_sym_db.RegisterMessage(MapInfo)

MapInfoList = _reflection.GeneratedProtocolMessageType('MapInfoList', (_message.Message,), {
  'DESCRIPTOR' : _MAPINFOLIST,
  '__module__' : 'smart.parking.smart_lp_parking_map_pb2'
  # @@protoc_insertion_point(class_scope:smart.parking.MapInfoList)
  })
_sym_db.RegisterMessage(MapInfoList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPERATINGTYPE._serialized_start=548
  _OPERATINGTYPE._serialized_end=618
  _LPMAPDATA._serialized_start=102
  _LPMAPDATA._serialized_end=364
  _MAPINFO._serialized_start=366
  _MAPINFO._serialized_end=489
  _MAPINFOLIST._serialized_start=491
  _MAPINFOLIST._serialized_end=546
# @@protoc_insertion_point(module_scope)
