def setupUi(self, MainWindow):
    MainWindow.setObjectName("MainWindow")
    MainWindow.resize(400, 150)
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
    self.verticalLayout.setObjectName("verticalLayout")
    self.lineEditFilePath = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditFilePath.setObjectName("lineEditFilePath")
    self.lineEditFilePath.setPlaceholderText("拖动文件到这里或点击选择文件")
    self.lineEditFilePath.setReadOnly(True)
    self.lineEditFilePath.setDragEnabled(True)
    self.lineEditFilePath.setAcceptDrops(True)
    self.lineEditFilePath.setStyleSheet("QLineEdit { border: 1px solid #ccc; padding: 5px; font-size: 14px; }")
    self.verticalLayout.addWidget(self.lineEditFilePath)
    self.pushButtonSelectFile = QtWidgets.QPushButton(self.centralwidget)
    self.pushButtonSelectFile.setObjectName("pushButtonSelectFile")
    self.pushButtonSelectFile.setText("选择文件")
    self.pushButtonSelectFile.setStyleSheet("QPushButton { background-color: #0078d7; color: white; padding: 5px 10px; border-radius: 5px; } QPushButton:hover { background-color: #005ba1; }")
    self.verticalLayout.addWidget(self.pushButtonSelectFile)
    self.labelInstruction = QtWidgets.QLabel(self.centralwidget)
    self.labelInstruction.setObjectName("labelInstruction")
    self.labelInstruction.setText("将文件拖动到这里或点击选择文件")
    self.labelInstruction.setStyleSheet("QLabel { color: #666; font-size: 12px; }")
    self.verticalLayout.addWidget(self.labelInstruction)
    MainWindow.setCentralWidget(self.centralwidget)