# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception/perception_frame_context.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import geometry_pb2 as common_dot_geometry__pb2
from proto.common.vehicle_state import vehicle_state_pb2 as common_dot_vehicle__state_dot_vehicle__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)perception/perception_frame_context.proto\x12\x14\x64\x65\x65proute.perception\x1a\x15\x63ommon/geometry.proto\x1a(common/vehicle_state/vehicle_state.proto\"\xbd\x01\n\x14SensorInputDebugInfo\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t\x12\x17\n\x0fmd5_hash_string\x18\x02 \x01(\t\x12\x17\n\x0ftimestamp_micro\x18\x03 \x01(\x03\x12+\n\x08position\x18\x04 \x01(\x0b\x32\x19.deeproute.common.Point3D\x12\x31\n\x0eroll_pitch_yaw\x18\x05 \x01(\x0b\x32\x19.deeproute.common.Point3D\"\xcc\x01\n\x0c\x46rameContext\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x38\n\x10input_car_states\x18\x02 \x03(\x0b\x32\x1e.deeproute.common.VehicleState\x12L\n\x18sensor_input_debug_infos\x18\x03 \x03(\x0b\x32*.deeproute.perception.SensorInputDebugInfo\x12\"\n\x1aline_manager_hidden_states\x18\x04 \x01(\x0c')



_SENSORINPUTDEBUGINFO = DESCRIPTOR.message_types_by_name['SensorInputDebugInfo']
_FRAMECONTEXT = DESCRIPTOR.message_types_by_name['FrameContext']
SensorInputDebugInfo = _reflection.GeneratedProtocolMessageType('SensorInputDebugInfo', (_message.Message,), {
  'DESCRIPTOR' : _SENSORINPUTDEBUGINFO,
  '__module__' : 'perception.perception_frame_context_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.SensorInputDebugInfo)
  })
_sym_db.RegisterMessage(SensorInputDebugInfo)

FrameContext = _reflection.GeneratedProtocolMessageType('FrameContext', (_message.Message,), {
  'DESCRIPTOR' : _FRAMECONTEXT,
  '__module__' : 'perception.perception_frame_context_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.FrameContext)
  })
_sym_db.RegisterMessage(FrameContext)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORINPUTDEBUGINFO._serialized_start=133
  _SENSORINPUTDEBUGINFO._serialized_end=322
  _FRAMECONTEXT._serialized_start=325
  _FRAMECONTEXT._serialized_end=529
# @@protoc_insertion_point(module_scope)
