# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dta/dta_onboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ta/dta_onboard.proto\x12\x0e\x64r.dta.onboard\"L\n\nDtaOnboard\x12>\n\x13single_trip_driving\x18\x01 \x01(\x0b\x32!.dr.dta.onboard.SingleTripDriving\"\xc7\x02\n\x11SingleTripDriving\x12\x0e\n\x06nav_id\x18\x01 \x01(\t\x12\x16\n\x0etotal_distance\x18\x02 \x01(\x01\x12\x14\n\x0cnoa_distance\x18\x03 \x01(\x01\x12\x14\n\x0clcc_distance\x18\x04 \x01(\x01\x12\x14\n\x0c\x61\x63\x63_distance\x18\x05 \x01(\x01\x12\x12\n\ntotal_time\x18\x06 \x01(\x04\x12\x10\n\x08noa_time\x18\x07 \x01(\x04\x12\x10\n\x08lcc_time\x18\x08 \x01(\x04\x12\x10\n\x08\x61\x63\x63_time\x18\t \x01(\x04\x12?\n\x13performance_metrics\x18\n \x01(\x0b\x32\".dr.dta.onboard.PerformanceMetrics\x12=\n\x12\x64riving_trajectory\x18\x0b \x01(\x0b\x32!.dr.dta.onboard.DrivingTrajectory\"G\n\x12PerformanceMetrics\x12\x31\n\x0cgrading_info\x18\x01 \x03(\x0b\x32\x1b.dr.dta.onboard.GradingInfo\"\x81\x04\n\x0bGradingInfo\x12?\n\rgrading_event\x18\x01 \x01(\x0e\x32(.dr.dta.onboard.GradingInfo.GradingEvent\x12\r\n\x05times\x18\x02 \x01(\r\"\xa1\x03\n\x0cGradingEvent\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x19\n\x15PASS_JUNCTION_SUCCESS\x10\x01\x12\x16\n\x12PASS_JUNCTION_FAIL\x10\x02\x12\x17\n\x13LANE_CHANGE_SUCCESS\x10\x03\x12\x14\n\x10LANE_CHANGE_FAIL\x10\x04\x12$\n INBOUND_OR_OUTBOUND_RAMP_SUCCESS\x10\x05\x12!\n\x1dINBOUND_OR_OUTBOUND_RAMP_FAIL\x10\x06\x12\x12\n\x0e\x44\x45TOUR_SUCCESS\x10\x07\x12\x0f\n\x0b\x44\x45TOUR_FAIL\x10\x08\x12\x15\n\x11YIELD_VRU_SUCCESS\x10\t\x12\x12\n\x0eYIELD_VRU_FAIL\x10\n\x12\x12\n\x0e\x43UT_IN_SUCCESS\x10\x0b\x12\x0f\n\x0b\x43UT_IN_FAIL\x10\x0c\x12\x1b\n\x17PASS_ROUNDABOUT_SUCCESS\x10\r\x12\x18\n\x14PASS_ROUNDABOUT_FAIL\x10\x0e\x12\x17\n\x13PASS_U_TURN_SUCCESS\x10\x0f\x12\x14\n\x10PASS_U_TURN_FAIL\x10\x10\"9\n\x11\x44rivingTrajectory\x12$\n\x05point\x18\x01 \x03(\x0b\x32\x15.dr.dta.onboard.Point\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x62\x06proto3')



_DTAONBOARD = DESCRIPTOR.message_types_by_name['DtaOnboard']
_SINGLETRIPDRIVING = DESCRIPTOR.message_types_by_name['SingleTripDriving']
_PERFORMANCEMETRICS = DESCRIPTOR.message_types_by_name['PerformanceMetrics']
_GRADINGINFO = DESCRIPTOR.message_types_by_name['GradingInfo']
_DRIVINGTRAJECTORY = DESCRIPTOR.message_types_by_name['DrivingTrajectory']
_POINT = DESCRIPTOR.message_types_by_name['Point']
_GRADINGINFO_GRADINGEVENT = _GRADINGINFO.enum_types_by_name['GradingEvent']
DtaOnboard = _reflection.GeneratedProtocolMessageType('DtaOnboard', (_message.Message,), {
  'DESCRIPTOR' : _DTAONBOARD,
  '__module__' : 'dta.dta_onboard_pb2'
  # @@protoc_insertion_point(class_scope:dr.dta.onboard.DtaOnboard)
  })
_sym_db.RegisterMessage(DtaOnboard)

SingleTripDriving = _reflection.GeneratedProtocolMessageType('SingleTripDriving', (_message.Message,), {
  'DESCRIPTOR' : _SINGLETRIPDRIVING,
  '__module__' : 'dta.dta_onboard_pb2'
  # @@protoc_insertion_point(class_scope:dr.dta.onboard.SingleTripDriving)
  })
_sym_db.RegisterMessage(SingleTripDriving)

PerformanceMetrics = _reflection.GeneratedProtocolMessageType('PerformanceMetrics', (_message.Message,), {
  'DESCRIPTOR' : _PERFORMANCEMETRICS,
  '__module__' : 'dta.dta_onboard_pb2'
  # @@protoc_insertion_point(class_scope:dr.dta.onboard.PerformanceMetrics)
  })
_sym_db.RegisterMessage(PerformanceMetrics)

GradingInfo = _reflection.GeneratedProtocolMessageType('GradingInfo', (_message.Message,), {
  'DESCRIPTOR' : _GRADINGINFO,
  '__module__' : 'dta.dta_onboard_pb2'
  # @@protoc_insertion_point(class_scope:dr.dta.onboard.GradingInfo)
  })
_sym_db.RegisterMessage(GradingInfo)

DrivingTrajectory = _reflection.GeneratedProtocolMessageType('DrivingTrajectory', (_message.Message,), {
  'DESCRIPTOR' : _DRIVINGTRAJECTORY,
  '__module__' : 'dta.dta_onboard_pb2'
  # @@protoc_insertion_point(class_scope:dr.dta.onboard.DrivingTrajectory)
  })
_sym_db.RegisterMessage(DrivingTrajectory)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'dta.dta_onboard_pb2'
  # @@protoc_insertion_point(class_scope:dr.dta.onboard.Point)
  })
_sym_db.RegisterMessage(Point)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DTAONBOARD._serialized_start=41
  _DTAONBOARD._serialized_end=117
  _SINGLETRIPDRIVING._serialized_start=120
  _SINGLETRIPDRIVING._serialized_end=447
  _PERFORMANCEMETRICS._serialized_start=449
  _PERFORMANCEMETRICS._serialized_end=520
  _GRADINGINFO._serialized_start=523
  _GRADINGINFO._serialized_end=1036
  _GRADINGINFO_GRADINGEVENT._serialized_start=619
  _GRADINGINFO_GRADINGEVENT._serialized_end=1036
  _DRIVINGTRAJECTORY._serialized_start=1038
  _DRIVINGTRAJECTORY._serialized_end=1095
  _POINT._serialized_start=1097
  _POINT._serialized_end=1137
# @@protoc_insertion_point(module_scope)
