# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odd/odd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.graph_match import graph_matching_pb2 as graph__match_dot_graph__matching__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rodd/odd.proto\x12\rdeeproute.odd\x1a graph_match/graph_matching.proto\"\xc8\x01\n\x17PreviewOddLimitAreaInfo\x12-\n\x08odd_type\x18\x01 \x01(\x0e\x32\x1b.deeproute.odd.OddLimitType\x12?\n\todd_range\x18\x02 \x03(\x0b\x32(.deeproute.graph_match.AmapLinkMatchInfoB\x02\x18\x01\x12=\n\x0bpoint_range\x18\x03 \x01(\x0b\x32(.deeproute.graph_match.AmapLinkMatchInfo\"U\n\x18PreviewRouteOddLimitInfo\x12\x39\n\todd_infos\x18\x01 \x03(\x0b\x32&.deeproute.odd.PreviewOddLimitAreaInfo\"k\n\x13OddLimitPreviewInfo\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12@\n\x0froute_odd_infos\x18\x02 \x03(\x0b\x32\'.deeproute.odd.PreviewRouteOddLimitInfo\"\xa2\x01\n\x10OddLimitAreaInfo\x12-\n\x08odd_type\x18\x01 \x01(\x0e\x32\x1b.deeproute.odd.OddLimitType\x12\x0f\n\x07link_id\x18\x02 \x03(\x04\x12\x12\n\nlink_index\x18\x03 \x03(\x05\x12\x1d\n\x15\x64istance_to_odd_start\x18\x04 \x01(\x01\x12\x1b\n\x13\x64istance_to_odd_end\x18\x05 \x01(\x01\"[\n\x0cOddLimitInfo\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x37\n\x0eodd_area_infos\x18\x02 \x03(\x0b\x32\x1f.deeproute.odd.OddLimitAreaInfo*\xed\x01\n\x0cOddLimitType\x12\x0f\n\x0bODD_UNKNOWN\x10\x00\x12\x11\n\rODD_REST_AREA\x10\x01\x12\x0c\n\x08ODD_TOLL\x10\x02\x12\x1a\n\x16ODD_GRAPH_MATCH_FAILED\x10\x03\x12\x0e\n\nODD_U_TURN\x10\x04\x12\x12\n\x0eODD_ROUNDABOUT\x10\x05\x12\x1d\n\x19ODD_SHARP_CORNER_JUNCTION\x10\x06\x12\x1c\n\x18ODD_FIVE_FORKED_JUNCTION\x10\x07\x12\x1b\n\x17ODD_SIX_FORKED_JUNCTION\x10\x08\x12\x11\n\rODD_TEMPORARY\x10\t')

_ODDLIMITTYPE = DESCRIPTOR.enum_types_by_name['OddLimitType']
OddLimitType = enum_type_wrapper.EnumTypeWrapper(_ODDLIMITTYPE)
ODD_UNKNOWN = 0
ODD_REST_AREA = 1
ODD_TOLL = 2
ODD_GRAPH_MATCH_FAILED = 3
ODD_U_TURN = 4
ODD_ROUNDABOUT = 5
ODD_SHARP_CORNER_JUNCTION = 6
ODD_FIVE_FORKED_JUNCTION = 7
ODD_SIX_FORKED_JUNCTION = 8
ODD_TEMPORARY = 9


_PREVIEWODDLIMITAREAINFO = DESCRIPTOR.message_types_by_name['PreviewOddLimitAreaInfo']
_PREVIEWROUTEODDLIMITINFO = DESCRIPTOR.message_types_by_name['PreviewRouteOddLimitInfo']
_ODDLIMITPREVIEWINFO = DESCRIPTOR.message_types_by_name['OddLimitPreviewInfo']
_ODDLIMITAREAINFO = DESCRIPTOR.message_types_by_name['OddLimitAreaInfo']
_ODDLIMITINFO = DESCRIPTOR.message_types_by_name['OddLimitInfo']
PreviewOddLimitAreaInfo = _reflection.GeneratedProtocolMessageType('PreviewOddLimitAreaInfo', (_message.Message,), {
  'DESCRIPTOR' : _PREVIEWODDLIMITAREAINFO,
  '__module__' : 'odd.odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.PreviewOddLimitAreaInfo)
  })
_sym_db.RegisterMessage(PreviewOddLimitAreaInfo)

PreviewRouteOddLimitInfo = _reflection.GeneratedProtocolMessageType('PreviewRouteOddLimitInfo', (_message.Message,), {
  'DESCRIPTOR' : _PREVIEWROUTEODDLIMITINFO,
  '__module__' : 'odd.odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.PreviewRouteOddLimitInfo)
  })
_sym_db.RegisterMessage(PreviewRouteOddLimitInfo)

OddLimitPreviewInfo = _reflection.GeneratedProtocolMessageType('OddLimitPreviewInfo', (_message.Message,), {
  'DESCRIPTOR' : _ODDLIMITPREVIEWINFO,
  '__module__' : 'odd.odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.OddLimitPreviewInfo)
  })
_sym_db.RegisterMessage(OddLimitPreviewInfo)

OddLimitAreaInfo = _reflection.GeneratedProtocolMessageType('OddLimitAreaInfo', (_message.Message,), {
  'DESCRIPTOR' : _ODDLIMITAREAINFO,
  '__module__' : 'odd.odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.OddLimitAreaInfo)
  })
_sym_db.RegisterMessage(OddLimitAreaInfo)

OddLimitInfo = _reflection.GeneratedProtocolMessageType('OddLimitInfo', (_message.Message,), {
  'DESCRIPTOR' : _ODDLIMITINFO,
  '__module__' : 'odd.odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.OddLimitInfo)
  })
_sym_db.RegisterMessage(OddLimitInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREVIEWODDLIMITAREAINFO.fields_by_name['odd_range']._options = None
  _PREVIEWODDLIMITAREAINFO.fields_by_name['odd_range']._serialized_options = b'\030\001'
  _ODDLIMITTYPE._serialized_start=724
  _ODDLIMITTYPE._serialized_end=961
  _PREVIEWODDLIMITAREAINFO._serialized_start=67
  _PREVIEWODDLIMITAREAINFO._serialized_end=267
  _PREVIEWROUTEODDLIMITINFO._serialized_start=269
  _PREVIEWROUTEODDLIMITINFO._serialized_end=354
  _ODDLIMITPREVIEWINFO._serialized_start=356
  _ODDLIMITPREVIEWINFO._serialized_end=463
  _ODDLIMITAREAINFO._serialized_start=466
  _ODDLIMITAREAINFO._serialized_end=628
  _ODDLIMITINFO._serialized_start=630
  _ODDLIMITINFO._serialized_end=721
# @@protoc_insertion_point(module_scope)
