# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/security_strategy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import module_status_pb2 as common_dot_module__status__pb2
from proto.common import error_code_pb2 as common_dot_error__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ommon/security_strategy.proto\x12\x0f\x64\x65\x65proute.proto\x1a\x1a\x63ommon/module_status.proto\x1a\x17\x63ommon/error_code.proto\"\xfd\x01\n\x13SecurityStrategyCMD\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x06source\x18\x02 \x01(\x0e\x32\x17.deeproute.proto.MODULE\x12,\n\x0b\x64\x65stination\x18\x03 \x01(\x0e\x32\x17.deeproute.proto.MODULE\x12\x35\n\x08strategy\x18\x04 \x01(\x0e\x32!.deeproute.proto.SecurityStrategyH\x00\x12\x45\n\x0fupdate_strategy\x18\x05 \x01(\x0b\x32*.deeproute.proto.UpdateSecurityStrategyCMDH\x00\x42\x05\n\x03\x63md\"\xaa\x01\n\x15SecurityStrategyCMDRP\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x06source\x18\x02 \x01(\x0e\x32\x17.deeproute.proto.MODULE\x12,\n\x0b\x64\x65stination\x18\x03 \x01(\x0e\x32\x17.deeproute.proto.MODULE\x12.\n\nerror_code\x18\x04 \x01(\x0b\x32\x1a.deeproute.common.StatusPb\"\xaf\x01\n\x17SecurityStrategyTrigger\x12\x34\n\nerror_code\x18\x01 \x03(\x0e\x32 .deeproute.proto.ModuleErrorCode\x12-\n\x0c\x65rror_module\x18\x02 \x03(\x0e\x32\x17.deeproute.proto.MODULE\x12/\n\x0elost_heartbeat\x18\x03 \x03(\x0e\x32\x17.deeproute.proto.MODULE\"\x89\x01\n\x17SecurityStrategyContext\x12\x39\n\x07trigger\x18\x01 \x01(\x0b\x32(.deeproute.proto.SecurityStrategyTrigger\x12\x33\n\x08strategy\x18\x02 \x01(\x0e\x32!.deeproute.proto.SecurityStrategy\"\xaf\x01\n\x19UpdateSecurityStrategyCMD\x12\x36\n\x15high_priority_modules\x18\x01 \x03(\x0e\x32\x17.deeproute.proto.MODULE\x12\x39\n\x07\x63ontext\x18\x02 \x03(\x0b\x32(.deeproute.proto.SecurityStrategyContext\x12\x1f\n\x17module_timeout_duration\x18\x03 \x01(\r*\x80\x01\n\x10SecurityStrategy\x12\x0f\n\x0bNOT_DEFINED\x10\x00\x12\x12\n\x0e\x45XIT_AUTO_MODE\x10\x01\x12\r\n\tPULL_OVER\x10\x02\x12\x12\n\x0e\x45MERGENCY_STOP\x10\x03\x12\r\n\tSLOW_DOWN\x10\x04\x12\x15\n\x11SLOW_DOWN_TO_STOP\x10\x05\x62\x06proto3')

_SECURITYSTRATEGY = DESCRIPTOR.enum_types_by_name['SecurityStrategy']
SecurityStrategy = enum_type_wrapper.EnumTypeWrapper(_SECURITYSTRATEGY)
NOT_DEFINED = 0
EXIT_AUTO_MODE = 1
PULL_OVER = 2
EMERGENCY_STOP = 3
SLOW_DOWN = 4
SLOW_DOWN_TO_STOP = 5


_SECURITYSTRATEGYCMD = DESCRIPTOR.message_types_by_name['SecurityStrategyCMD']
_SECURITYSTRATEGYCMDRP = DESCRIPTOR.message_types_by_name['SecurityStrategyCMDRP']
_SECURITYSTRATEGYTRIGGER = DESCRIPTOR.message_types_by_name['SecurityStrategyTrigger']
_SECURITYSTRATEGYCONTEXT = DESCRIPTOR.message_types_by_name['SecurityStrategyContext']
_UPDATESECURITYSTRATEGYCMD = DESCRIPTOR.message_types_by_name['UpdateSecurityStrategyCMD']
SecurityStrategyCMD = _reflection.GeneratedProtocolMessageType('SecurityStrategyCMD', (_message.Message,), {
  'DESCRIPTOR' : _SECURITYSTRATEGYCMD,
  '__module__' : 'common.security_strategy_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.proto.SecurityStrategyCMD)
  })
_sym_db.RegisterMessage(SecurityStrategyCMD)

SecurityStrategyCMDRP = _reflection.GeneratedProtocolMessageType('SecurityStrategyCMDRP', (_message.Message,), {
  'DESCRIPTOR' : _SECURITYSTRATEGYCMDRP,
  '__module__' : 'common.security_strategy_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.proto.SecurityStrategyCMDRP)
  })
_sym_db.RegisterMessage(SecurityStrategyCMDRP)

SecurityStrategyTrigger = _reflection.GeneratedProtocolMessageType('SecurityStrategyTrigger', (_message.Message,), {
  'DESCRIPTOR' : _SECURITYSTRATEGYTRIGGER,
  '__module__' : 'common.security_strategy_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.proto.SecurityStrategyTrigger)
  })
_sym_db.RegisterMessage(SecurityStrategyTrigger)

SecurityStrategyContext = _reflection.GeneratedProtocolMessageType('SecurityStrategyContext', (_message.Message,), {
  'DESCRIPTOR' : _SECURITYSTRATEGYCONTEXT,
  '__module__' : 'common.security_strategy_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.proto.SecurityStrategyContext)
  })
_sym_db.RegisterMessage(SecurityStrategyContext)

UpdateSecurityStrategyCMD = _reflection.GeneratedProtocolMessageType('UpdateSecurityStrategyCMD', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESECURITYSTRATEGYCMD,
  '__module__' : 'common.security_strategy_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.proto.UpdateSecurityStrategyCMD)
  })
_sym_db.RegisterMessage(UpdateSecurityStrategyCMD)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SECURITYSTRATEGY._serialized_start=1030
  _SECURITYSTRATEGY._serialized_end=1158
  _SECURITYSTRATEGYCMD._serialized_start=105
  _SECURITYSTRATEGYCMD._serialized_end=358
  _SECURITYSTRATEGYCMDRP._serialized_start=361
  _SECURITYSTRATEGYCMDRP._serialized_end=531
  _SECURITYSTRATEGYTRIGGER._serialized_start=534
  _SECURITYSTRATEGYTRIGGER._serialized_end=709
  _SECURITYSTRATEGYCONTEXT._serialized_start=712
  _SECURITYSTRATEGYCONTEXT._serialized_end=849
  _UPDATESECURITYSTRATEGYCMD._serialized_start=852
  _UPDATESECURITYSTRATEGYCMD._serialized_end=1027
# @@protoc_insertion_point(module_scope)
