# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivers/sensor_can_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64rivers/sensor_can_msg.proto\x12\x11\x64\x65\x65proute.drivers\"\xfd\x01\n\x06\x43\x61nMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x16\n\x0e\x61rbitration_id\x18\x02 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\r\x12\x0b\n\x03\x64lc\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x16\n\x0eis_extended_id\x18\x06 \x01(\x08\x12\x16\n\x0eis_error_frame\x18\x07 \x01(\x08\x12\x17\n\x0fis_remote_frame\x18\x08 \x01(\x08\x12\r\n\x05is_fd\x18\t \x01(\x08\x12\r\n\x05is_rx\x18\n \x01(\x08\x12\x16\n\x0e\x62itrate_switch\x18\x0b \x01(\x08\x12\x1d\n\x15\x65rror_state_indicator\x18\x0c \x01(\x08\"T\n\x06\x43\x61nPkt\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0f\n\x07msg_num\x18\x02 \x01(\x04\x12&\n\x03msg\x18\x03 \x03(\x0b\x32\x19.deeproute.drivers.CanMsg\"R\n\nCanMsgSmpl\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0e\n\x06\x63\x61n_id\x18\x02 \x01(\r\x12\x13\n\x0blen_channel\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"\x8d\x01\n\rCanRawArray5K\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x13\n\x0b\x63\x61nframenum\x18\x02 \x01(\r\x12\x17\n\x0frolling_counter\x18\x03 \x01(\r\x12.\n\x07\x63\x61n_raw\x18\x04 \x03(\x0b\x32\x1d.deeproute.drivers.CanMsgSmpl\x12\x0b\n\x03\x63rc\x18\x05 \x01(\r')



_CANMSG = DESCRIPTOR.message_types_by_name['CanMsg']
_CANPKT = DESCRIPTOR.message_types_by_name['CanPkt']
_CANMSGSMPL = DESCRIPTOR.message_types_by_name['CanMsgSmpl']
_CANRAWARRAY5K = DESCRIPTOR.message_types_by_name['CanRawArray5K']
CanMsg = _reflection.GeneratedProtocolMessageType('CanMsg', (_message.Message,), {
  'DESCRIPTOR' : _CANMSG,
  '__module__' : 'drivers.sensor_can_msg_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.CanMsg)
  })
_sym_db.RegisterMessage(CanMsg)

CanPkt = _reflection.GeneratedProtocolMessageType('CanPkt', (_message.Message,), {
  'DESCRIPTOR' : _CANPKT,
  '__module__' : 'drivers.sensor_can_msg_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.CanPkt)
  })
_sym_db.RegisterMessage(CanPkt)

CanMsgSmpl = _reflection.GeneratedProtocolMessageType('CanMsgSmpl', (_message.Message,), {
  'DESCRIPTOR' : _CANMSGSMPL,
  '__module__' : 'drivers.sensor_can_msg_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.CanMsgSmpl)
  })
_sym_db.RegisterMessage(CanMsgSmpl)

CanRawArray5K = _reflection.GeneratedProtocolMessageType('CanRawArray5K', (_message.Message,), {
  'DESCRIPTOR' : _CANRAWARRAY5K,
  '__module__' : 'drivers.sensor_can_msg_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.CanRawArray5K)
  })
_sym_db.RegisterMessage(CanRawArray5K)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CANMSG._serialized_start=52
  _CANMSG._serialized_end=305
  _CANPKT._serialized_start=307
  _CANPKT._serialized_end=391
  _CANMSGSMPL._serialized_start=393
  _CANMSGSMPL._serialized_end=475
  _CANRAWARRAY5K._serialized_start=478
  _CANRAWARRAY5K._serialized_end=619
# @@protoc_insertion_point(module_scope)
