# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odd/gwm_odd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11odd/gwm_odd.proto\x12\rdeeproute.odd\"|\n\nODDSection\x12\x12\n\nstep_begin\x18\x01 \x01(\x05\x12\x10\n\x08step_end\x18\x02 \x01(\x05\x12\x12\n\nlink_begin\x18\x03 \x01(\x05\x12\x10\n\x08link_end\x18\x04 \x01(\x05\x12\x11\n\tpnt_begin\x18\x05 \x01(\x05\x12\x0f\n\x07pnt_end\x18\x06 \x01(\x05\"e\n\x0bODDPathInfo\x12\x0f\n\x07path_id\x18\x01 \x01(\x04\x12\x14\n\x0cmatch_status\x18\x02 \x01(\x05\x12/\n\x0codd_sections\x18\x03 \x03(\x0b\x32\x19.deeproute.odd.ODDSection\"D\n\x0eODDMatchResult\x12\x32\n\x0eodd_path_infos\x18\x01 \x03(\x0b\x32\x1a.deeproute.odd.ODDPathInfob\x06proto3')



_ODDSECTION = DESCRIPTOR.message_types_by_name['ODDSection']
_ODDPATHINFO = DESCRIPTOR.message_types_by_name['ODDPathInfo']
_ODDMATCHRESULT = DESCRIPTOR.message_types_by_name['ODDMatchResult']
ODDSection = _reflection.GeneratedProtocolMessageType('ODDSection', (_message.Message,), {
  'DESCRIPTOR' : _ODDSECTION,
  '__module__' : 'odd.gwm_odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.ODDSection)
  })
_sym_db.RegisterMessage(ODDSection)

ODDPathInfo = _reflection.GeneratedProtocolMessageType('ODDPathInfo', (_message.Message,), {
  'DESCRIPTOR' : _ODDPATHINFO,
  '__module__' : 'odd.gwm_odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.ODDPathInfo)
  })
_sym_db.RegisterMessage(ODDPathInfo)

ODDMatchResult = _reflection.GeneratedProtocolMessageType('ODDMatchResult', (_message.Message,), {
  'DESCRIPTOR' : _ODDMATCHRESULT,
  '__module__' : 'odd.gwm_odd_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.odd.ODDMatchResult)
  })
_sym_db.RegisterMessage(ODDMatchResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ODDSECTION._serialized_start=36
  _ODDSECTION._serialized_end=160
  _ODDPATHINFO._serialized_start=162
  _ODDPATHINFO._serialized_end=263
  _ODDMATCHRESULT._serialized_start=265
  _ODDMATCHRESULT._serialized_end=333
# @@protoc_insertion_point(module_scope)
