# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry/trigger_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19sentry/trigger_info.proto\x12\x0e\x64\x65\x65proute.trip\"\xa5\x01\n\x0bTriggerInfo\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x19\n\x11\x62\x61\x63kward_time_sec\x18\x02 \x01(\r\x12\x18\n\x10\x66orward_time_sec\x18\x03 \x01(\r\x12\x10\n\x08priority\x18\x04 \x01(\r\x12\x1b\n\x13system_timestamp_ns\x18\x05 \x01(\x04\x12\x11\n\tbags_name\x18\x06 \x03(\t\x12\x10\n\x08\x65vent_id\x18\x07 \x01(\r')



_TRIGGERINFO = DESCRIPTOR.message_types_by_name['TriggerInfo']
TriggerInfo = _reflection.GeneratedProtocolMessageType('TriggerInfo', (_message.Message,), {
  'DESCRIPTOR' : _TRIGGERINFO,
  '__module__' : 'sentry.trigger_info_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.trip.TriggerInfo)
  })
_sym_db.RegisterMessage(TriggerInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIGGERINFO._serialized_start=46
  _TRIGGERINFO._serialized_end=211
# @@protoc_insertion_point(module_scope)
