# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart/navigation/smart_odd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n smart/navigation/smart_odd.proto\x12\tsmart.odd\"|\n\nODDSection\x12\x12\n\nstep_begin\x18\x01 \x01(\x05\x12\x10\n\x08step_end\x18\x02 \x01(\x05\x12\x12\n\nlink_begin\x18\x03 \x01(\x05\x12\x10\n\x08link_end\x18\x04 \x01(\x05\x12\x11\n\tpnt_begin\x18\x05 \x01(\x05\x12\x0f\n\x07pnt_end\x18\x06 \x01(\x05\"a\n\x0bODDPathInfo\x12\x0f\n\x07path_id\x18\x01 \x01(\x05\x12\x14\n\x0cmatch_status\x18\x02 \x01(\x05\x12+\n\x0codd_sections\x18\x03 \x03(\x0b\x32\x15.smart.odd.ODDSection\"@\n\x0eODDMatchResult\x12.\n\x0eodd_path_infos\x18\x01 \x03(\x0b\x32\x16.smart.odd.ODDPathInfob\x06proto3')



_ODDSECTION = DESCRIPTOR.message_types_by_name['ODDSection']
_ODDPATHINFO = DESCRIPTOR.message_types_by_name['ODDPathInfo']
_ODDMATCHRESULT = DESCRIPTOR.message_types_by_name['ODDMatchResult']
ODDSection = _reflection.GeneratedProtocolMessageType('ODDSection', (_message.Message,), {
  'DESCRIPTOR' : _ODDSECTION,
  '__module__' : 'smart.navigation.smart_odd_pb2'
  # @@protoc_insertion_point(class_scope:smart.odd.ODDSection)
  })
_sym_db.RegisterMessage(ODDSection)

ODDPathInfo = _reflection.GeneratedProtocolMessageType('ODDPathInfo', (_message.Message,), {
  'DESCRIPTOR' : _ODDPATHINFO,
  '__module__' : 'smart.navigation.smart_odd_pb2'
  # @@protoc_insertion_point(class_scope:smart.odd.ODDPathInfo)
  })
_sym_db.RegisterMessage(ODDPathInfo)

ODDMatchResult = _reflection.GeneratedProtocolMessageType('ODDMatchResult', (_message.Message,), {
  'DESCRIPTOR' : _ODDMATCHRESULT,
  '__module__' : 'smart.navigation.smart_odd_pb2'
  # @@protoc_insertion_point(class_scope:smart.odd.ODDMatchResult)
  })
_sym_db.RegisterMessage(ODDMatchResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ODDSECTION._serialized_start=47
  _ODDSECTION._serialized_end=171
  _ODDPATHINFO._serialized_start=173
  _ODDPATHINFO._serialized_end=270
  _ODDMATCHRESULT._serialized_start=272
  _ODDMATCHRESULT._serialized_end=336
# @@protoc_insertion_point(module_scope)
