# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drapi/lp/lp_adas_health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64rapi/lp/lp_adas_health.proto\x12\x06lp.hmi\"*\n\x0e\x41\x64\x61sHealthData\x12\x18\n\x10\x61\x64\x61s_health_data\x18\x01 \x01(\x0c\x62\x06proto3')



_ADASHEALTHDATA = DESCRIPTOR.message_types_by_name['AdasHealthData']
AdasHealthData = _reflection.GeneratedProtocolMessageType('AdasHealthData', (_message.Message,), {
  'DESCRIPTOR' : _ADASHEALTHDATA,
  '__module__' : 'drapi.lp.lp_adas_health_pb2'
  # @@protoc_insertion_point(class_scope:lp.hmi.AdasHealthData)
  })
_sym_db.RegisterMessage(AdasHealthData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADASHEALTHDATA._serialized_start=41
  _ADASHEALTHDATA._serialized_end=83
# @@protoc_insertion_point(module_scope)
