# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drapi/lp/lp_edr_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64rapi/lp/lp_edr_status.proto\x12\x06\x64r.edr\"\xb6\x03\n\x0b\x45\x64rSdStatus\x12\x34\n\x06\x65\x64r_sd\x18\x01 \x01(\x0e\x32$.dr.edr.EdrSdStatus.EdrSdMountStatus\x12\x41\n\x10\x65\x64r_record_error\x18\x02 \x01(\x0e\x32\".dr.edr.EdrSdStatus.EdrRecordErrorH\x00\x88\x01\x01\"u\n\x10\x45\x64rSdMountStatus\x12!\n\x1d\x45\x44R_SD_MOUNT_STATUS_UNDEFINED\x10\x00\x12\x1f\n\x1b\x45\x44R_SD_MOUNT_STATUS_UNMOUNT\x10\x01\x12\x1d\n\x19\x45\x44R_SD_MOUNT_STATUS_MOUNT\x10\x02\"\xa1\x01\n\x0e\x45\x64rRecordError\x12\x1e\n\x1a\x45\x44R_RECORD_ERROR_UNDEFINED\x10\x00\x12!\n\x1d\x45\x44R_RECORD_ERROR_RECORD_ERROR\x10\x01\x12 \n\x1c\x45\x44R_RECORD_ERROR_WRITE_ERROR\x10\x02\x12*\n&EDR_RECORD_ERROR_RECORD_PATH_EXCEPTION\x10\x03\x42\x13\n\x11_edr_record_errorb\x06proto3')



_EDRSDSTATUS = DESCRIPTOR.message_types_by_name['EdrSdStatus']
_EDRSDSTATUS_EDRSDMOUNTSTATUS = _EDRSDSTATUS.enum_types_by_name['EdrSdMountStatus']
_EDRSDSTATUS_EDRRECORDERROR = _EDRSDSTATUS.enum_types_by_name['EdrRecordError']
EdrSdStatus = _reflection.GeneratedProtocolMessageType('EdrSdStatus', (_message.Message,), {
  'DESCRIPTOR' : _EDRSDSTATUS,
  '__module__' : 'drapi.lp.lp_edr_status_pb2'
  # @@protoc_insertion_point(class_scope:dr.edr.EdrSdStatus)
  })
_sym_db.RegisterMessage(EdrSdStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EDRSDSTATUS._serialized_start=41
  _EDRSDSTATUS._serialized_end=479
  _EDRSDSTATUS_EDRSDMOUNTSTATUS._serialized_start=177
  _EDRSDSTATUS_EDRSDMOUNTSTATUS._serialized_end=294
  _EDRSDSTATUS_EDRRECORDERROR._serialized_start=297
  _EDRSDSTATUS_EDRRECORDERROR._serialized_end=458
# @@protoc_insertion_point(module_scope)
