# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: someip_adapter/power_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"someip_adapter/power_manager.proto\x12\x1c\x64\x65\x65proute.someip_adapter.gwm\"1\n\x10McuToSocPowerMsg\x12\x1d\n\x15\x44svPowerMgmtMsg_Array\x18\x01 \x01(\x0c\"\xb3\x01\n\x10SocToMcuPowerMsg\x12N\n\x08response\x18\x01 \x01(\x0e\x32<.deeproute.someip_adapter.gwm.SocToMcuPowerMsg.PowerResponse\"O\n\rPowerResponse\x12\x11\n\rRESPONSE_WAIT\x10\x00\x12\x16\n\x12RESPONSE_COMPLETED\x10\x01\x12\x13\n\x0fRESPONSE_FAILED\x10\x02\"\xab\x01\n\x14PowerMgtToAppRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\x0c\x12L\n\x05reset\x18\x02 \x01(\x0e\x32=.deeproute.someip_adapter.gwm.PowerMgtToAppRequest.PowerReset\"3\n\nPowerReset\x12\x15\n\x11INVALID_OPERATION\x10\x00\x12\x0e\n\nHARD_RESET\x10\x01\"\xa7\x01\n\x15PowerMgtToAppResponse\x12T\n\x06result\x18\x01 \x01(\x0e\x32\x44.deeproute.someip_adapter.gwm.PowerMgtToAppResponse.PowerResetResult\"8\n\x10PowerResetResult\x12\x11\n\rRESET_UNKNOWN\x10\x00\x12\x11\n\rRESET_HANDLED\x10\x01\x62\x06proto3')



_MCUTOSOCPOWERMSG = DESCRIPTOR.message_types_by_name['McuToSocPowerMsg']
_SOCTOMCUPOWERMSG = DESCRIPTOR.message_types_by_name['SocToMcuPowerMsg']
_POWERMGTTOAPPREQUEST = DESCRIPTOR.message_types_by_name['PowerMgtToAppRequest']
_POWERMGTTOAPPRESPONSE = DESCRIPTOR.message_types_by_name['PowerMgtToAppResponse']
_SOCTOMCUPOWERMSG_POWERRESPONSE = _SOCTOMCUPOWERMSG.enum_types_by_name['PowerResponse']
_POWERMGTTOAPPREQUEST_POWERRESET = _POWERMGTTOAPPREQUEST.enum_types_by_name['PowerReset']
_POWERMGTTOAPPRESPONSE_POWERRESETRESULT = _POWERMGTTOAPPRESPONSE.enum_types_by_name['PowerResetResult']
McuToSocPowerMsg = _reflection.GeneratedProtocolMessageType('McuToSocPowerMsg', (_message.Message,), {
  'DESCRIPTOR' : _MCUTOSOCPOWERMSG,
  '__module__' : 'someip_adapter.power_manager_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.someip_adapter.gwm.McuToSocPowerMsg)
  })
_sym_db.RegisterMessage(McuToSocPowerMsg)

SocToMcuPowerMsg = _reflection.GeneratedProtocolMessageType('SocToMcuPowerMsg', (_message.Message,), {
  'DESCRIPTOR' : _SOCTOMCUPOWERMSG,
  '__module__' : 'someip_adapter.power_manager_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.someip_adapter.gwm.SocToMcuPowerMsg)
  })
_sym_db.RegisterMessage(SocToMcuPowerMsg)

PowerMgtToAppRequest = _reflection.GeneratedProtocolMessageType('PowerMgtToAppRequest', (_message.Message,), {
  'DESCRIPTOR' : _POWERMGTTOAPPREQUEST,
  '__module__' : 'someip_adapter.power_manager_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.someip_adapter.gwm.PowerMgtToAppRequest)
  })
_sym_db.RegisterMessage(PowerMgtToAppRequest)

PowerMgtToAppResponse = _reflection.GeneratedProtocolMessageType('PowerMgtToAppResponse', (_message.Message,), {
  'DESCRIPTOR' : _POWERMGTTOAPPRESPONSE,
  '__module__' : 'someip_adapter.power_manager_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.someip_adapter.gwm.PowerMgtToAppResponse)
  })
_sym_db.RegisterMessage(PowerMgtToAppResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MCUTOSOCPOWERMSG._serialized_start=68
  _MCUTOSOCPOWERMSG._serialized_end=117
  _SOCTOMCUPOWERMSG._serialized_start=120
  _SOCTOMCUPOWERMSG._serialized_end=299
  _SOCTOMCUPOWERMSG_POWERRESPONSE._serialized_start=220
  _SOCTOMCUPOWERMSG_POWERRESPONSE._serialized_end=299
  _POWERMGTTOAPPREQUEST._serialized_start=302
  _POWERMGTTOAPPREQUEST._serialized_end=473
  _POWERMGTTOAPPREQUEST_POWERRESET._serialized_start=422
  _POWERMGTTOAPPREQUEST_POWERRESET._serialized_end=473
  _POWERMGTTOAPPRESPONSE._serialized_start=476
  _POWERMGTTOAPPRESPONSE._serialized_end=643
  _POWERMGTTOAPPRESPONSE_POWERRESETRESULT._serialized_start=587
  _POWERMGTTOAPPRESPONSE_POWERRESETRESULT._serialized_end=643
# @@protoc_insertion_point(module_scope)
