# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivers/camera/camera_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#drivers/camera/camera_command.proto\x12\x18\x64\x65\x65proute.drivers.camera\"]\n\rCameraCommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x39\n\nvideo_type\x18\x02 \x01(\x0e\x32#.deeproute.drivers.camera.VideoTypeH\x00\x42\x05\n\x03\x63md*M\n\tVideoType\x12\x16\n\x12VIDEO_TYPE_UNKNOWN\x10\x00\x12\x0b\n\x07\x43MS_OFF\x10\x01\x12\x0c\n\x08\x43MS_LEFT\x10\x02\x12\r\n\tCMS_RIGHT\x10\x03')

_VIDEOTYPE = DESCRIPTOR.enum_types_by_name['VideoType']
VideoType = enum_type_wrapper.EnumTypeWrapper(_VIDEOTYPE)
VIDEO_TYPE_UNKNOWN = 0
CMS_OFF = 1
CMS_LEFT = 2
CMS_RIGHT = 3


_CAMERACOMMAND = DESCRIPTOR.message_types_by_name['CameraCommand']
CameraCommand = _reflection.GeneratedProtocolMessageType('CameraCommand', (_message.Message,), {
  'DESCRIPTOR' : _CAMERACOMMAND,
  '__module__' : 'drivers.camera.camera_command_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.drivers.camera.CameraCommand)
  })
_sym_db.RegisterMessage(CameraCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOTYPE._serialized_start=160
  _VIDEOTYPE._serialized_end=237
  _CAMERACOMMAND._serialized_start=65
  _CAMERACOMMAND._serialized_end=158
# @@protoc_insertion_point(module_scope)
