# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drdtu/dtu_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64rdtu/dtu_data.proto\x12\x12\x64\x65\x65proute.dtu.data\"H\n\tErrorCode\x12*\n\x08\x65rr_code\x18\x01 \x01(\x0e\x32\x18.deeproute.dtu.data.Code\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\"\xb6\x01\n\x0cTravelStatus\x12\x12\n\ntime_stamp\x18\x01 \x01(\r\x12\x14\n\x0ctarget_index\x18\x02 \x01(\r\x12\x1a\n\x12remaining_distance\x18\x03 \x01(\x02\x12\x16\n\x0eremaining_time\x18\x04 \x01(\x02\x12\x1d\n\x15start_to_cur_distance\x18\x05 \x01(\x02\x12\x19\n\x11start_to_cur_time\x18\x06 \x01(\x02\x12\x0e\n\x06\x63md_id\x18\x07 \x01(\t\"\xc3\x01\n\rContainerInfo\x12\x10\n\x08\x64istance\x18\x01 \x01(\x01\x12=\n\x04type\x18\x02 \x01(\x0e\x32/.deeproute.dtu.data.ContainerInfo.ContainerType\"a\n\rContainerType\x12\x1a\n\x16\x43ONTAINER_TYPE_NOT_SET\x10\x00\x12\x0f\n\x0bTWENTY_FEET\x10\x01\x12\x0e\n\nFORTY_FEET\x10\x02\x12\x13\n\x0f\x46ORTY_FIVE_FEET\x10\x03\"\xa3\x01\n\x0f\x43ontainerStatus\x12\x15\n\rhas_container\x18\x01 \x01(\x08\x12;\n\x10\x61s_one_container\x18\x02 \x01(\x0b\x32!.deeproute.dtu.data.ContainerInfo\x12<\n\x11\x61s_two_containers\x18\x03 \x03(\x0b\x32!.deeproute.dtu.data.ContainerInfo*\x99\x01\n\x06Module\x12\x07\n\x03\x44TU\x10\x00\x12\x0b\n\x07PLANNER\x10\x01\x12\x0b\n\x07\x43ONTROL\x10\x02\x12\x10\n\x0cLOCALIZATION\x10\x03\x12\x0e\n\nPERCEPTION\x10\x04\x12\n\n\x06\x43\x41NBUS\x10\x05\x12\x0e\n\nVISUALIZER\x10\x06\x12\x0b\n\x07ROUTING\x10\x07\x12\x11\n\rLOCAL_ROUTING\x10\x08\x12\x0e\n\nMAP_ENGINE\x10\t*\x1f\n\x04\x43ode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x62\x06proto3')

_MODULE = DESCRIPTOR.enum_types_by_name['Module']
Module = enum_type_wrapper.EnumTypeWrapper(_MODULE)
_CODE = DESCRIPTOR.enum_types_by_name['Code']
Code = enum_type_wrapper.EnumTypeWrapper(_CODE)
DTU = 0
PLANNER = 1
CONTROL = 2
LOCALIZATION = 3
PERCEPTION = 4
CANBUS = 5
VISUALIZER = 6
ROUTING = 7
LOCAL_ROUTING = 8
MAP_ENGINE = 9
SUCCESS = 0
FAILED = 1


_ERRORCODE = DESCRIPTOR.message_types_by_name['ErrorCode']
_TRAVELSTATUS = DESCRIPTOR.message_types_by_name['TravelStatus']
_CONTAINERINFO = DESCRIPTOR.message_types_by_name['ContainerInfo']
_CONTAINERSTATUS = DESCRIPTOR.message_types_by_name['ContainerStatus']
_CONTAINERINFO_CONTAINERTYPE = _CONTAINERINFO.enum_types_by_name['ContainerType']
ErrorCode = _reflection.GeneratedProtocolMessageType('ErrorCode', (_message.Message,), {
  'DESCRIPTOR' : _ERRORCODE,
  '__module__' : 'drdtu.dtu_data_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.dtu.data.ErrorCode)
  })
_sym_db.RegisterMessage(ErrorCode)

TravelStatus = _reflection.GeneratedProtocolMessageType('TravelStatus', (_message.Message,), {
  'DESCRIPTOR' : _TRAVELSTATUS,
  '__module__' : 'drdtu.dtu_data_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.dtu.data.TravelStatus)
  })
_sym_db.RegisterMessage(TravelStatus)

ContainerInfo = _reflection.GeneratedProtocolMessageType('ContainerInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERINFO,
  '__module__' : 'drdtu.dtu_data_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.dtu.data.ContainerInfo)
  })
_sym_db.RegisterMessage(ContainerInfo)

ContainerStatus = _reflection.GeneratedProtocolMessageType('ContainerStatus', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERSTATUS,
  '__module__' : 'drdtu.dtu_data_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.dtu.data.ContainerStatus)
  })
_sym_db.RegisterMessage(ContainerStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODULE._serialized_start=668
  _MODULE._serialized_end=821
  _CODE._serialized_start=823
  _CODE._serialized_end=854
  _ERRORCODE._serialized_start=44
  _ERRORCODE._serialized_end=116
  _TRAVELSTATUS._serialized_start=119
  _TRAVELSTATUS._serialized_end=301
  _CONTAINERINFO._serialized_start=304
  _CONTAINERINFO._serialized_end=499
  _CONTAINERINFO_CONTAINERTYPE._serialized_start=402
  _CONTAINERINFO_CONTAINERTYPE._serialized_end=499
  _CONTAINERSTATUS._serialized_start=502
  _CONTAINERSTATUS._serialized_end=665
# @@protoc_insertion_point(module_scope)
